title: Saez Lab
description: Webpage for the Saez lab at scripps.

url: https://SaezLabTSRI.github.io
permalink: pretty
plugins:
  - jekyll-octicons
collections:
  members: 
    output: False
  alumni:
    output: False
  publications:
    output: False
